import pickle
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
from sklearn.metrics import confusion_matrix, classification_report
import spacy
import nltk
from nltk.corpus import stopwords
import string
import unicodedata
import random
import numpy as np

# Descargar stopwords de nltk
nltk.download('stopwords')

# Cargar el modelo de Spacy para español
nlp = spacy.load('es_core_news_sm')

# Obtener la lista de stopwords en español y eliminar los interrogativos
stop_words = set(stopwords.words('spanish'))

# Lista de puntuación con caracteres en español
punctuation = string.punctuation

# Cargar las palabras del archivo diccionario_general.txt
with open('diccionario_general.txt', 'r', encoding='utf-8') as f:
    custom_stop_words = set(f.read().splitlines())

# Combinar las stopwords y las palabras personalizadas
stop_words.update(custom_stop_words)

# Función de preprocesamiento
def preprocess(text):
    # Eliminar acentos
    nfkd_form = unicodedata.normalize('NFKD', text)
    text = "".join([c for c in nfkd_form if not unicodedata.combining(c)])
    # Convertir a minúsculas
    text = text.lower()
    # Quitar signos de puntuación
    text = text.translate(str.maketrans('', '', punctuation))
    # Tokenizar y lematizar
    doc = nlp(text)
    tokens = [token.lemma_ for token in doc if token.lemma_ not in stop_words and token.lemma_ not in punctuation]
    return ' '.join(tokens)

# Datos de entrenamiento
data = [
    # Consultar saldo 172 ejemplos
    ("quiero informacion sobre como consultar mi saldo", "consultar_saldo"),
    ("Como consulto mi saldo", "consultar_saldo"),
    ("hola buenas tardes, tengo dudas sobre como consultar mi saldo, ayudame", "consultar_saldo"),
    ("hola tengo una tarjeta nueva, como consulto mi saldo?", "consultar_saldo"),
    ("¿De qué manera puedo consultar mi saldo?", "consultar_saldo"),
    ("Necesito pasos para verificar el saldo de mi tarjeta, ¿puedes ayudarme?", "consultar_saldo"),
    ("¿Me podrías explicar cómo acceder a mi saldo?", "consultar_saldo"),
    ("¿Cuál es el método para revisar el saldo de mi tarjeta?", "consultar_saldo"),
    ("¿Qué debo hacer para obtener mi saldo actual?", "consultar_saldo"),
    ("Por favor, explícame cómo puedo checar el saldo de mi cuenta", "consultar_saldo"),
    ("¿Cómo puedo ver el saldo disponible en mi tarjeta de crédito?", "consultar_saldo"),
    ("Necesito instrucciones detalladas para consultar mi saldo.", "consultar_saldo"),
    ("¿Cuál es el procedimiento para obtener información sobre mi saldo bancario?", "consultar_saldo"),
    ("Dime los pasos para acceder al saldo de mi tarjeta.", "consultar_saldo"),
    ("¿Cómo puedo consultar mi saldo?", "consultar_saldo"),
    ("Instrucciones para consultar mi saldo", "consultar_saldo"),
    ("Proceso para consultar mi saldo", "consultar_saldo"),
    ("Quiero saber cómo consultar mi saldo", "consultar_saldo"),
    ("¿Cómo revisar mi saldo?", "consultar_saldo"),
    ("Guía para consultar mi saldo", "consultar_saldo"),
    ("Ayuda para consultar mi saldo", "consultar_saldo"),
    ("Detalles sobre la consulta de saldo", "consultar_saldo"),
    ("Método para consultar mi saldo", "consultar_saldo"),
    ("Forma de consultar mi saldo", "consultar_saldo"),
    ("¿Cómo puedo ver mi saldo?", "consultar_saldo"),
    ("Necesito saber cómo consultar mi saldo", "consultar_saldo"),
    ("Dime cómo puedo consultar mi saldo", "consultar_saldo"),
    ("¿Cómo se consulta el saldo?", "consultar_saldo"),
    ("¿Qué debo hacer para consultar mi saldo?", "consultar_saldo"),
    ("Explicación de cómo consultar mi saldo", "consultar_saldo"),
    ("Quiero saber el proceso para consultar mi saldo", "consultar_saldo"),
    ("Pasos para consultar mi saldo", "consultar_saldo"),
    ("¿Cómo verificar mi saldo?", "consultar_saldo"),
    ("Información sobre la consulta de saldo", "consultar_saldo"),
    ("¿Cómo hago para consultar mi saldo?", "consultar_saldo"),
    ("Explícame cómo consultar mi saldo", "consultar_saldo"),
    ("¿Me puedes decir cómo consultar mi saldo?", "consultar_saldo"),
    ("Quiero saber cómo ver mi saldo", "consultar_saldo"),
    ("¿Cómo revisar el saldo de mi cuenta?", "consultar_saldo"),
    ("¿Cómo consultar el saldo disponible?", "consultar_saldo"),
    ("¿Cómo puedo ver el saldo de mi cuenta?", "consultar_saldo"),
    ("¿Cómo puedo saber cuánto dinero tengo?", "consultar_saldo"),
    ("¿Cómo puedo saber cuánto dinero tengo disponible?", "consultar_saldo"),
    ("¿Cómo puedo saber cuánto saldo tengo?", "consultar_saldo"),
    ("¿Cómo puedo saber cuánto saldo tengo disponible?", "consultar_saldo"),
    ("¿Cómo puedo saber cuánto dinero tengo en la cuenta?", "consultar_saldo"),
    ("Necesito saber mi saldo", "consultar_saldo"),
    ("¿Cuál es el procedimiento para verificar mi balance?", "consultar_saldo"),
    ("Dime cómo puedo revisar mi estado de cuenta", "consultar_saldo"),
    ("¿Cómo puedo obtener información sobre mi cuenta bancaria?", "consultar_saldo"),
    ("Quiero saber cómo puedo conocer mi disponibilidad de fondos", "consultar_saldo"),
    ("¿Cómo puedo obtener detalles sobre mi situación financiera?", "consultar_saldo"),
    ("Explícame cómo puedo consultar mi balance actual", "consultar_saldo"),
    ("¿Cuál es la forma de obtener información sobre mis finanzas?", "consultar_saldo"),
    ("Necesito saber cómo puedo verificar mi saldo bancario", "consultar_saldo"),
    ("¿Cuál es la manera de obtener información sobre mis recursos financieros?", "consultar_saldo"),
    ("Explícame cómo puedo revisar mi balance disponible", "consultar_saldo"),
    ("¿Cuál es el proceso para obtener detalles sobre mi cuenta?", "consultar_saldo"),
    ("Necesito saber cómo puedo consultar mi situación económica", "consultar_saldo"),
    ("Dime cómo puedo obtener información sobre mi balance bancario", "consultar_saldo"),
    ("¿Cómo puedo conocer mi estado financiero actual?", "consultar_saldo"),
    ("Quiero saber cómo puedo obtener un resumen de mis finanzas", "consultar_saldo"),
    ("¿Cuál es la forma de obtener detalles sobre mis transacciones?", "consultar_saldo"),
    ("Explícame cómo puedo consultar mi balance actualizado", "consultar_saldo"),
    ("¿Cuál es la manera de obtener información sobre mis movimientos financieros?", "consultar_saldo"),
    ("¿Podrías explicarme cómo consultar mi balance?", "consultar_saldo"),
    ("Necesito asesoramiento sobre cómo obtener información de mi cuenta", "consultar_saldo"),
    ("¿Me puedes guiar en cómo obtener mi estado financiero?", "consultar_saldo"),
    ("Quiero saber cómo solicitar detalles sobre mis finanzas", "consultar_saldo"),
    ("¿Puedes darme instrucciones sobre cómo obtener mi saldo actual?", "consultar_saldo"),
    ("Necesito orientación sobre cómo acceder a mi información de cuenta", "consultar_saldo"),
    ("¿Podrías indicarme cómo obtener mi balance bancario?", "consultar_saldo"),
    ("Quisiera saber cómo obtener información sobre mis recursos financieros", "consultar_saldo"),
    ("¿Me puedes asesorar sobre cómo consultar mi disponibilidad de fondos?", "consultar_saldo"),
    ("Necesito instrucciones sobre cómo obtener detalles de mi situación económica", "consultar_saldo"),
    ("¿Cuál es el saldo de mi tarjeta?", "consultar_saldo"),
    ("Quiero saber si mi saldo esta en 0 para poder cancelar mi tarjeta", "consultar_saldo"),
    ("hola necesito saber cuento dinero tengo en la cuenta", "consultar_saldo"),
    ("¿Cuánto hay en mi tarjeta?", "consultar_saldo"),
    ("¿Cuánto saldo tengo en mi tarjeta?", "consultar_saldo"),
    ("¿Cuánto saldo tengo en mi tarjeta de crédito?", "consultar_saldo"),
    ("¿Cuánto saldo tengo en mi tarjeta de débito?", "consultar_saldo"),
    ("¿Puedes mostrarme el saldo de mi tarjeta?", "consultar_saldo"),
    ("¿Me puedes decir cuánto saldo tengo en mi tarjeta?", "consultar_saldo"),
    ("Necesito consultar el saldo de mi tarjeta", "consultar_saldo"),
    ("Quiero revisar el saldo de mi tarjeta", "consultar_saldo"),
    ("¿Puedes decirme cuánto saldo tengo en mi tarjeta?", "consultar_saldo"),
    ("¿Cuánto dinero tengo en mi tarjeta?", "consultar_saldo"),
    ("¿Cuánto saldo tengo disponible en mi tarjeta?", "consultar_saldo"),
    ("¿Cuánto saldo tengo en mi tarjeta de crédito?", "consultar_saldo"),
    ("¿Cuánto saldo tengo en mi tarjeta de débito?", "consultar_saldo"),
    ("¿Cuánto saldo tengo en mi tarjeta bancaria?", "consultar_saldo"),
    ("Quiero saber mi saldo", "consultar_saldo"),
    ("Dame el saldo de mi tarjeta", "consultar_saldo"),
    ("Dame mi saldo", "consultar_saldo"),
    ("Por favor, dame mi saldo", "consultar_saldo"),
    ("¿Cuánto tengo en mi tarjeta?", "consultar_saldo"),
    ("Puedes darme mi saldo", "consultar_saldo"),
    ("Dime el dinero de mi cuenta", "consultar_saldo"),
    ("Da mi saldo", "consultar_saldo"),
    ("muestrame mi saldo", "consultar_saldo"),
    ("muestra mi saldo", "consultar_saldo"),
    ("¿Cuánto tengo en mi cuenta?", "consultar_saldo"),
    ("Dame el saldo", "consultar_saldo"),
    ("hola buen dia, quiero saber mis saldo", "consultar_saldo"),
    ("consulta saldo", "consultar_saldo"),
    ("consulta mi saldo", "consultar_saldo"),
    ("Quiero mi saldo", "consultar_saldo"),
    ("¿Cuál es mi saldo?", "consultar_saldo"),
    ("Consulta de saldo", "consultar_saldo"),
    ("Necesito ver mi saldo", "consultar_saldo"),
    ("consulta mi saldo actual", "consultar_saldo"),
    ("Mostrar saldo", "consultar_saldo"),
    ("Saldo disponible", "consultar_saldo"),
    ("¿Cuánto dinero tengo?", "consultar_saldo"),
    ("¿Cuál es el saldo de mi cuenta?", "consultar_saldo"),
    ("Me gustaría conocer mi saldo", "consultar_saldo"),
    ("Enséñame mi saldo", "consultar_saldo"),
    ("Saldo actual, por favor", "consultar_saldo"),
    ("Quisiera revisar mi saldo", "consultar_saldo"),
    ("Dime mi saldo", "consultar_saldo"),
    ("Dime mi saldo actual", "consultar_saldo"),
    ("Revisión de saldo", "consultar_saldo"),
    ("¿Cuánto tengo en la cuenta?", "consultar_saldo"),
    ("¿Cuánto hay en mi saldo?", "consultar_saldo"),
    ("Saldo de mi cuenta", "consultar_saldo"),
    ("Revisa mi saldo", "consultar_saldo"),
    ("Muéstrame mi saldo", "consultar_saldo"),
    ("Consulta cuánto tengo", "consultar_saldo"),
    ("¿Qué saldo tengo?", "consultar_saldo"),
    ("Por favor, infórmame sobre mi saldo", "consultar_saldo"),
    ("Solicito ver el saldo de mi cuenta", "consultar_saldo"),
    ("¿Me puedes decir cuánto saldo tengo?", "consultar_saldo"),
    ("Necesito consultar mi saldo disponible", "consultar_saldo"),
    ("Quiero revisar el saldo de mi cuenta", "consultar_saldo"),
    ("¿Puedes mostrarme mi saldo?", "consultar_saldo"),
    ("Estado de mi saldo, por favor", "consultar_saldo"),
    ("Necesito saber cuánto dinero tengo disponible.", "consultar_saldo"),
    ("¿Podrías decirme el saldo actual de mi cuenta?", "consultar_saldo"),
    ("¿Cuánto dinero tengo en la cuenta?", "consultar_saldo"),
    ("¿Cuál es el saldo actual de mi cuenta?", "consultar_saldo"),
    ("¿Cuánto saldo tengo en mi cuenta?", "consultar_saldo"),
    ("¿Puedes decirme cuánto dinero tengo?", "consultar_saldo"),
    ("¿Cuánto dinero tengo en mi cuenta?", "consultar_saldo"),
    ("¿Cuánto saldo tengo disponible?", "consultar_saldo"),
    ("¿Cuánto saldo tengo en mi tarjeta?", "consultar_saldo"),
    ("¿Puedes decirme cuánto dinero tengo en mi cuenta?", "consultar_saldo"),
    ("Necesito conocer mi balance financiero", "consultar_saldo"),
    ("¿Cuál es el estado de mi cuenta?", "consultar_saldo"),
    ("Quiero saber cuánto dinero tengo disponible", "consultar_saldo"),
    ("¿Puedes mostrarme mi balance?", "consultar_saldo"),
    ("Necesito verificar mi situación financiera", "consultar_saldo"),
    ("¿Cuánto tengo en mi cuenta bancaria?", "consultar_saldo"),
    ("Dame información sobre mi saldo", "consultar_saldo"),
    ("¿Puedes decirme cuánto dinero tengo en mi tarjeta de débito?", "consultar_saldo"),
    ("¿Cuál es mi balance actual?", "consultar_saldo"),
    ("Hola, quiero verificar cuánto dinero hay en mi cuenta", "consultar_saldo"),
    ("¿Puedes informarme sobre el saldo disponible?", "consultar_saldo"),
    ("Necesito saber el estado de mi saldo", "consultar_saldo"),
    ("¿Cuánto dinero tengo en mi tarjeta bancaria?", "consultar_saldo"),
    ("¿Cuál es el saldo que tengo en mi cuenta?", "consultar_saldo"),
    ("Por favor, dime el saldo de mi tarjeta", "consultar_saldo"),
    ("¿Me puedes mostrar el saldo que tengo?", "consultar_saldo"),
    ("Quiero consultar el saldo de mi cuenta", "consultar_saldo"),
    ("¿Cuánto dinero tengo disponible en mi tarjeta?", "consultar_saldo"),
    ("Necesito revisar cuánto saldo tengo", "consultar_saldo"),
    ("¿Podrías decirme cuánto hay en mi cuenta?", "consultar_saldo"),
    ("Enséñame el saldo de mi cuenta, por favor", "consultar_saldo"),
    ("Solicito información sobre mi saldo actual", "consultar_saldo"),
    ("¿Puedes decirme el saldo que tengo en la tarjeta?", "consultar_saldo"),
    ("Me gustaría saber cuánto dinero tengo disponible", "consultar_saldo"),
    ("Dime cuánto saldo tengo en mi tarjeta, por favor", "consultar_saldo"),
    ("Muéstrame el saldo actual de mi cuenta", "consultar_saldo"),
    ("Quiero saber el balance de mi tarjeta", "consultar_saldo"),
    ("Necesito conocer el saldo de mi cuenta bancaria", "consultar_saldo"),
    ("Quisisera consultar mi saldo porfavor", "consultar_saldo"),


    # Cancelar tarjeta 151 ejemplos
    ("Quiero bloquear mi tarjeta", "cancelar_tarjeta"),
    ("Cancelar tarjeta", "cancelar_tarjeta"),  
    ("hola buenos dias, me podrias ayudar cancelando mi carjeta", "cancelar_tarjeta"),
    ("Deseo cancelar mi tarjeta", "cancelar_tarjeta"),
    ("Bloquea mi cuenta", "cancelar_tarjeta"),
    ("Quiero anular mi tarjeta", "cancelar_tarjeta"),
    ("Detener mi tarjeta", "cancelar_tarjeta"),
    ("me gustaria dar de baja mi tarjeta", "cancelar_tarjeta"),
    ("Suspender cuenta", "cancelar_tarjeta"),
    ("Eliminar mi cuenta", "cancelar_tarjeta"),
    ("Cerrar cuenta de tarjeta", "cancelar_tarjeta"),
    ("Desactivar tarjeta", "cancelar_tarjeta"),
    ("Dar de baja mi tarjeta", "cancelar_tarjeta"),
    ("¿Cómo puedo cancelar mi tarjeta?", "cancelar_tarjeta"),
    ("Necesito cancelar mi cuenta", "cancelar_tarjeta"),
    ("Quiero dar de baja mi cuenta", "cancelar_tarjeta"),
    ("Por favor, cancela mi tarjeta", "cancelar_tarjeta"),
    ("Me gustaría suspender mi tarjeta", "cancelar_tarjeta"),
    ("Quiero bloquear mi tarjeta de crédito", "cancelar_tarjeta"),
    ("Bloquea mi tarjeta de débito", "cancelar_tarjeta"),
    ("Cancelar mi tarjeta inmediatamente", "cancelar_tarjeta"),
    ("¿Cómo suspender mi tarjeta?", "cancelar_tarjeta"),
    ("Darme de baja de mi tarjeta", "cancelar_tarjeta"),
    ("Quiero que bloquees mi tarjeta", "cancelar_tarjeta"),
    ("Cancela mi tarjeta por favor", "cancelar_tarjeta"),
    ("Bloquea la tarjeta", "cancelar_tarjeta"),
    ("Anula mi tarjeta", "cancelar_tarjeta"),
    ("Cierra mi tarjeta", "cancelar_tarjeta"),
    ("Desactiva mi tarjeta", "cancelar_tarjeta"),
    ("Dame de baja la tarjeta", "cancelar_tarjeta"),
    ("Quiero cancelar mi tarjeta de crédito", "cancelar_tarjeta"),
    ("Quiero cancelar mi tarjeta", "cancelar_tarjeta"),
    ("Necesito bloquear mi tarjeta de débito", "cancelar_tarjeta"),
    ("Por favor, anula mi tarjeta de crédito", "cancelar_tarjeta"),
    ("Quiero cancelar mi cuenta", "cancelar_tarjeta"),
    ("Deseo cerrar mi cuenta de tarjeta de débito", "cancelar_tarjeta"),
    ("Quiero desactivar mi tarjeta de crédito", "cancelar_tarjeta"),
    ("Cancelar mi tarjeta lo más pronto posible", "cancelar_tarjeta"),
    ("Quiero cancelar mi plástico", "cancelar_tarjeta"),
    ("Deseo dar de baja mi tarjeta bancaria", "cancelar_tarjeta"),
    ("Necesito bloquear mi medio de pago", "cancelar_tarjeta"),
    ("Quiero suspender mi método de pago", "cancelar_tarjeta"),
    ("Por favor, desactiva mi medio de financiamiento", "cancelar_tarjeta"),
    ("Me gustaría cerrar mi forma de pago", "cancelar_tarjeta"),
    ("Quiero cancelar mi instrumento de crédito", "cancelar_tarjeta"),
    ("Deseo anular mi medio de pago", "cancelar_tarjeta"),
    ("Necesito bloquear mi tarjeta de crédito", "cancelar_tarjeta"),
    ("Por favor, suspender mi tarjeta de débito", "cancelar_tarjeta"),
    ("Deseo cerrar mi tarjeta de crédito", "cancelar_tarjeta"),
    ("Quiero desactivar mi tarjeta de débito bancaria", "cancelar_tarjeta"),
    ("Necesito bloquear mi tarjeta personal", "cancelar_tarjeta"),
    ("Quiero cancelar mi tarjeta de débito personal", "cancelar_tarjeta"),
    ("Por favor, suspender mi tarjeta de crédito corporativa", "cancelar_tarjeta"),
    ("Quiero dar de baja mi tarjeta de débito personal", "cancelar_tarjeta"),
    ("Deseo cerrar mi tarjeta de crédito personal", "cancelar_tarjeta"),
    ("Quiero desactivar mi tarjeta de débito personal", "cancelar_tarjeta"),
    ("Necesito bloquear mi tarjeta de crédito corporativa", "cancelar_tarjeta"),
    ("Por favor, anula mi tarjeta de débito personal", "cancelar_tarjeta"),
    ("Quiero cancelar mi tarjeta de crédito personal", "cancelar_tarjeta"),
    ("Deseo dar de baja mi cuenta de débito bancaria", "cancelar_tarjeta"),
    ("Necesito bloquear mi cuenta de crédito personal", "cancelar_tarjeta"),
    ("Por favor, suspender mi ceunta de débito personal", "cancelar_tarjeta"),
    ("Deseo cerrar mi tarjeta de débito personal", "cancelar_tarjeta"),
    ("Quiero dar de baja mi plástico", "cancelar_tarjeta"),
    ("Cancelar mi cuenta de crédito", "cancelar_tarjeta"),
    ("Deseo suspender mi medio de pago", "cancelar_tarjeta"),
    ("Por favor, anula mi instrumento de crédito", "cancelar_tarjeta"),
    ("Quiero bloquear mi forma de financiamiento", "cancelar_tarjeta"),
    ("Cancelar mi método de pago", "cancelar_tarjeta"),
    ("Darme de baja de mi cuenta bancaria", "cancelar_tarjeta"),
    ("Quiero suspender mi medio de financiamiento", "cancelar_tarjeta"),
    ("Por favor, desactiva mi forma de pago", "cancelar_tarjeta"),
    ("Me gustaría cerrar mi instrumento de crédito", "cancelar_tarjeta"),
    ("Quisiera cancelar mi tarjeta", "cancelar_tarjeta"),
    ("Como doy de baja mi tarjeta", "cancelar_tarjeta"),
    ("Ayudame a cancelar mi tarjeta", "cancelar_tarjeta"),
    ("perdi mi tarjeta y la quiero cancelar, como la cancelo?", "cancelar_tarjeta"),
    ("¿Cómo puedo cancelar mi tarjeta?", "cancelar_tarjeta"),
    ("¿Cómo anulo mi medio de pago?", "cancelar_tarjeta"),
    ("como cancelo mi tarjeta", "cancelar_tarjeta"),
    ("¿Cómo puedo cancelar mi plástico?", "cancelar_tarjeta"),
    ("Instrucciones para cancelar mi tarjeta", "cancelar_tarjeta"),
    ("Proceso para cancelar mi tarjeta", "cancelar_tarjeta"),
    ("Quiero saber cómo cancelar mi tarjeta", "cancelar_tarjeta"),
    ("Dime cómo dar de baja mi tarjeta", "cancelar_tarjeta"),
    ("¿Cómo anular mi tarjeta?", "cancelar_tarjeta"),
    ("Guía para cancelar mi tarjeta", "cancelar_tarjeta"),
    ("Ayuda para cancelar mi tarjeta", "cancelar_tarjeta"),
    ("Detalles sobre la cancelación de mi tarjeta", "cancelar_tarjeta"),
    ("Método para cancelar mi tarjeta", "cancelar_tarjeta"),
    ("Forma de cancelar mi tarjeta", "cancelar_tarjeta"),
    ("¿Cómo puedo bloquear mi tarjeta?", "cancelar_tarjeta"),
    ("Necesito saber cómo cancelar mi tarjeta", "cancelar_tarjeta"),
    ("Dime cómo puedo cancelar mi tarjeta", "cancelar_tarjeta"),
    ("¿Cómo se cancela una tarjeta?", "cancelar_tarjeta"),
    ("¿Qué debo hacer para cancelar mi tarjeta?", "cancelar_tarjeta"),
    ("Explicación de cómo cancelar mi tarjeta", "cancelar_tarjeta"),
    ("Quiero saber el proceso para cancelar mi tarjeta", "cancelar_tarjeta"),
    ("Pasos para cancelar mi tarjeta", "cancelar_tarjeta"),
    ("¿Cómo suspender mi tarjeta?", "cancelar_tarjeta"),
    ("Información sobre la cancelación de mi tarjeta", "cancelar_tarjeta"),
    ("¿Cómo hago para cancelar mi tarjeta?", "cancelar_tarjeta"),
    ("Explícame cómo cancelar mi tarjeta", "cancelar_tarjeta"),
    ("¿Me puedes decir cómo cancelar mi tarjeta?", "cancelar_tarjeta"),
    ("Quiero saber cómo dar de baja mi tarjeta", "cancelar_tarjeta"),
    ("¿Cómo anular mi tarjeta de crédito?", "cancelar_tarjeta"),
    ("¿Cómo desactivar mi tarjeta?", "cancelar_tarjeta"),
    ("¿Cómo cerrar mi tarjeta?", "cancelar_tarjeta"),
    ("¿Cómo dar de baja mi tarjeta?", "cancelar_tarjeta"),
    ("¿Cómo bloquear mi tarjeta de débito?", "cancelar_tarjeta"),
    ("¿Cómo cancelar mi tarjeta inmediatamente?", "cancelar_tarjeta"),
    ("¿Cómo suspender mi tarjeta de crédito?", "cancelar_tarjeta"),
    ("¿Cómo dar de baja mi tarjeta de débito?", "cancelar_tarjeta"),
    ("que tengo que hacer para cancelar mi tarjeta", "cancelar_tarjeta"),
    ("¿Qué debo hacer para suspender mi instrumento de crédito?", "cancelar_tarjeta"),
    ("Explicación de cómo cancelar mi método de pago", "cancelar_tarjeta"),
    ("Quiero saber el procedimiento para cerrar mi forma de pago", "cancelar_tarjeta"),
    ("Pasos para desactivar mi medio de financiamiento", "cancelar_tarjeta"),
    ("¿Cómo puedo bloquear mi tarjeta de crédito?", "cancelar_tarjeta"),
    ("¿Cómo cancelar mi plástico inmediatamente?", "cancelar_tarjeta"),
    ("¿Cómo suspender mi tarjeta de débito?", "cancelar_tarjeta"),
    ("¿Cómo dar de baja mi tarjeta de crédito?", "cancelar_tarjeta"),
    ("¿Cómo puedo cancelar mi tarjeta de débito?", "cancelar_tarjeta"),
    ("¿Cómo puedo cancelar mi medio de pago lo más pronto posible?", "cancelar_tarjeta"),
    ("¿Cómo puedo cancelar mi cuenta?", "cancelar_tarjeta"),
    ("Quiero dar de baja mi cuenta", "cancelar_tarjeta"),
    ("Por favor, cancela mi cuenta", "cancelar_tarjeta"),
    ("Me gustaría suspender mi cuenta", "cancelar_tarjeta"),
    ("¿Cuál es el proceso para cancelar mi cuenta?", "cancelar_tarjeta"),
    ("Necesito información sobre la cancelación de cuenta", "cancelar_tarjeta"),
    ("¿Cómo puedo cerrar mi cuenta?", "cancelar_tarjeta"),
    ("Dime cómo puedo dar de baja mi cuenta", "cancelar_tarjeta"),
    ("¿Cómo anulo mi cuenta?", "cancelar_tarjeta"),
    ("¿Qué debo hacer para suspender mi cuenta?", "cancelar_tarjeta"),
    ("Explicación de cómo cancelar mi cuenta", "cancelar_tarjeta"),
    ("Quiero saber el procedimiento para cancelar mi cuenta", "cancelar_tarjeta"),
    ("Pasos para dar de baja mi cuenta", "cancelar_tarjeta"),
    ("¿Cómo puedo desactivar mi cuenta?", "cancelar_tarjeta"),
    ("Necesito saber cómo cerrar mi cuenta", "cancelar_tarjeta"),
    ("Dime cómo puedo anular mi cuenta", "cancelar_tarjeta"),
    ("¿Cómo puedo dar de baja mi cuenta?", "cancelar_tarjeta"),
    ("¿Cómo puedo bloquear mi cuenta?", "cancelar_tarjeta"),
    ("¿Cómo cancelo mi cuenta inmediatamente?", "cancelar_tarjeta"),
    ("¿Cómo suspendo mi cuenta de crédito?", "cancelar_tarjeta"),
    ("¿Cómo doy de baja mi cuenta de débito?", "cancelar_tarjeta"),
    ("¿Cómo puedo cerrar mi cuenta de crédito?", "cancelar_tarjeta"),
    ("¿Cómo desactivo mi cuenta de débito bancaria?", "cancelar_tarjeta"),
    ("¿Cómo bloqueo mi cuenta personal?", "cancelar_tarjeta"),
    ("¿Cómo cancelo mi cuenta de débito personal?", "cancelar_tarjeta"),
    ("¿Cómo anulo mi cuenta de crédito personal?", "cancelar_tarjeta"),
    ("¿Cómo desactivo mi cuenta de débito personal?", "cancelar_tarjeta"),
    ("¿Cómo bloqueo mi cuenta de crédito corporativa?", "cancelar_tarjeta"),

  
    
    # Informes sobre préstamos 78 ejemplos
    ("Quiero un credito", "info_prestamo"),
    ("tengo una duda sobre los prestamos, puedes darme informacion?", "info_prestamo"),
    ("hablame sobre sus prestamos", "info_prestamo"),
    ("Dame informes sobre prestamos", "info_prestamo"),
    ("necesito un crédito", "info_prestamo"),
    ("¿Puedo obtener un préstamo?", "info_prestamo"),
    ("Necesito saber que prestamos manejan", "info_prestamo"),
    ("Quiero solicitar un préstamo", "info_prestamo"),
    ("¿Cuáles son los requisitos para obtener un préstamo?", "info_prestamo"),
    ("Necesito dinero prestado", "info_prestamo"),
    ("¿Cómo puedo obtener financiamiento?", "info_prestamo"),
    ("Estoy interesado en un préstamo", "info_prestamo"),
    ("¿Cuál es la tasa de interés para un préstamo?", "info_prestamo"),
    ("¿Cuánto puedo pedir prestado?", "info_prestamo"),
    ("Quiero saber más sobre los préstamos", "info_prestamo"),
    ("¿Cuál es el plazo de pago para un préstamo?", "info_prestamo"),
    ("Estoy buscando opciones de préstamo", "info_prestamo"),
    ("¿Cuál es el proceso para obtener un préstamo?", "info_prestamo"),
    ("Necesito dinero en préstamo", "info_prestamo"),
    ("¿Cuánto tiempo tarda en aprobarse un préstamo?", "info_prestamo"),
    ("Quiero información sobre los préstamos disponibles", "info_prestamo"),
    ("¿Cuál es el monto máximo que puedo solicitar?", "info_prestamo"),
    ("Estoy considerando solicitar un préstamo", "info_prestamo"),
    ("¿Cuál es la forma de pago para un préstamo?", "info_prestamo"),
    ("Necesito un préstamo urgente", "info_prestamo"),
    ("¿Cuáles son las condiciones para obtener un préstamo?", "info_prestamo"),
    ("Quiero conocer las opciones de préstamo", "info_prestamo"),
    ("¿Cuál es el plazo máximo para pagar un préstamo?", "info_prestamo"),
    ("Estoy buscando un préstamo con buenas tasas de interés", "info_prestamo"),
    ("¿Cuánto tiempo tengo para pagar un préstamo?", "info_prestamo"),
    ("Quiero saber si califico para un préstamo", "info_prestamo"),
    ("¿Cuál es el proceso de aprobación para un préstamo?", "info_prestamo"),
    ("Necesito información sobre los préstamos personales", "info_prestamo"),
    ("¿Cuál es la cantidad mínima que puedo solicitar?", "info_prestamo"),
    ("Estoy interesado en un préstamo a largo plazo", "info_prestamo"),
    ("¿Cuál es la tasa de interés anual para un préstamo?", "info_prestamo"),
    ("Quiero saber si puedo obtener un préstamo sin garantía", "info_prestamo"),
    ("¿Puedo conseguir un préstamo?", "info_prestamo"),
    ("Quisiera pedir un crédito", "info_prestamo"),
    ("¿Qué se necesita para solicitar un financiamiento?", "info_prestamo"),
    ("Me gustaría saber sobre los préstamos disponibles", "info_prestamo"),
    ("¿Cómo puedo acceder a un préstamo?", "info_prestamo"),
    ("Necesito financiamiento, ¿qué opciones tengo?", "info_prestamo"),
    ("Estoy buscando un préstamo, ¿me pueden ayudar?", "info_prestamo"),
    ("¿Cuál es la tasa de interés de los créditos?", "info_prestamo"),
    ("¿Cuál es el límite de un préstamo?", "info_prestamo"),
    ("Quiero más detalles sobre cómo obtener un préstamo", "info_prestamo"),
    ("¿En cuánto tiempo se paga un préstamo?", "info_prestamo"),
    ("Busco opciones de financiamiento, ¿qué tienen?", "info_prestamo"),
    ("¿Cómo funciona el proceso de préstamo?", "info_prestamo"),
    ("Necesito un crédito, ¿qué debo hacer?", "info_prestamo"),
    ("hola como obtengo un credito?", "info_prestamo"),
    ("¿Cuánto tiempo tarda la aprobación de un crédito?", "info_prestamo"),
    ("Quisiera información sobre los diferentes tipos de préstamos", "info_prestamo"),
    ("¿Cuál es el monto máximo que puedo pedir en un crédito?", "info_prestamo"),
    ("Estoy pensando en solicitar un crédito", "info_prestamo"),
    ("¿Cuáles son las opciones de pago para un préstamo?", "info_prestamo"),
    ("Necesito un préstamo con urgencia", "info_prestamo"),
    ("¿Cuáles son los términos y condiciones para un crédito?", "info_prestamo"),
    ("Quiero explorar mis opciones de financiamiento", "info_prestamo"),
    ("¿Puedo obtener un préstamo sin garantía?", "info_prestamo"),
    ("Quiero solicitar un préstamo personal", "info_prestamo"),
    ("¿Cuál es el proceso para obtener un crédito?", "info_prestamo"),
    ("Necesito financiamiento para mi negocio", "info_prestamo"),
    ("¿Cuánto dinero puedo pedir prestado?", "info_prestamo"),
    ("Estoy interesado en un préstamo a corto plazo", "info_prestamo"),
    ("¿Cuál es la tasa de interés para un crédito?", "info_prestamo"),
    ("Quiero saber si califico para un préstamo hipotecario", "info_prestamo"),
    ("¿Cuál es el plazo máximo para pagar un préstamo personal?", "info_prestamo"),
    ("Estoy buscando opciones de financiamiento para un proyecto", "info_prestamo"),
    ("¿Cuánto tiempo tengo para pagar un préstamo estudiantil?", "info_prestamo"),
    ("Quiero saber si puedo obtener un préstamo con mal crédito", "info_prestamo"),
    ("¿Cuál es el monto mínimo que puedo solicitar en un crédito?", "info_prestamo"),
    ("Estoy interesado en un préstamo para comprar un auto", "info_prestamo"),
    ("¿Cuál es la tasa de interés anual para un préstamo personal?", "info_prestamo"),
    ("Quiero saber si puedo obtener un préstamo sin historial crediticio", "info_prestamo"),
    ("¿Cuál es el límite de crédito para un préstamo de consolidación?", "info_prestamo"),
    ("Estoy buscando un préstamo para remodelar mi casa", "info_prestamo"),
    ("Hola buen dia me gustaria saber que tipo de prestamos manejan", "info_prestamo"),  
    ("hola que tal buen dia, estoy interesado en solicitar un prestamo, podrias darme informacion", "info_prestamo"),  
    ("Puedes darme informacion sobre sus prestamos", "info_prestamo"), 
    ("Necestio saber si puedo obtener un prestamo", "info_prestamo"), 


    #informacion seguros 80 ejemplos
    ("Dame informes sobre seguros", "info_seguros"),
    ("hola buenos dias, que tipo de seguros puedo pedir?", "info_seguros"),
    ("Dame informes sobre planes de seguros", "info_seguros"),
    ("¿Cómo puedo obtener información sobre seguros de vida?", "info_seguros"),
    ("Hola, ¿me puedes ayudar con información sobre seguros de auto?", "info_seguros"),
    ("Necesito saber más sobre los seguros de viaje, ¿puedes ayudarme?", "info_seguros"),
    ("¿Qué opciones tengo para asegurar mi vida?", "info_seguros"),
    ("Quisiera detalles sobre los seguros de coche, por favor", "info_seguros"),
    ("Hola, ¿qué seguros de viaje ofrecen?", "info_seguros"),
    ("¿Cómo funciona un seguro de vida?", "info_seguros"),
    ("Hola, ¿puedes darme información sobre los seguros de auto?", "info_seguros"),
    ("¿Cuáles son las coberturas de los seguros de viaje?", "info_seguros"),
    ("¿Qué beneficios tiene un seguro de vida?", "info_seguros"),
    ("Necesito un seguro para mi coche, ¿qué opciones tengo?", "info_seguros"),
    ("¿Qué incluye un seguro de viaje?", "info_seguros"),
    ("Hola, ¿cómo puedo contratar un seguro de vida?", "info_seguros"),
    ("Quiero asegurar mi auto, ¿qué debo hacer?", "info_seguros"),
    ("¿Qué tipos de seguros de viaje tienen?", "info_seguros"),
    ("¿Me puedes explicar qué es un seguro de vida?", "info_seguros"),
    ("¿Qué cubre un seguro de auto?", "info_seguros"),
    ("Hola, estoy interesado en un seguro de viaje, ¿me das información?", "info_seguros"),
    ("¿Cuánto cuesta un seguro de vida?", "info_seguros"),
    ("Quiero saber más sobre los seguros de coche", "info_seguros"),
    ("Hola, ¿me puedes hablar sobre los seguros de viaje?", "info_seguros"),
    ("¿Qué ventajas tiene un seguro de vida?", "info_seguros"),
    ("Necesito asegurar mi carro, ¿qué opciones tengo?", "info_seguros"),
    ("¿Qué cubren los seguros de viaje?", "info_seguros"),
    ("¿Cómo puedo contratar un seguro de vida?", "info_seguros"),
    ("Hola, quiero información sobre seguros de auto", "info_seguros"),
    ("¿Qué incluye un seguro de viaje?", "info_seguros"),
    ("¿Me puedes dar información sobre los seguros de vida?", "info_seguros"),
    ("Quiero asegurar mi auto, ¿qué opciones hay?", "info_seguros"),
    ("Hola, ¿qué opciones hay para asegurar un viaje?", "info_seguros"),
    ("¿Cómo funciona un seguro de vida?", "info_seguros"),
    ("¿Qué beneficios tiene un seguro de coche?", "info_seguros"),
    ("Hola, quiero saber más sobre seguros de viaje", "info_seguros"),
    ("¿Cuáles son las coberturas de un seguro de vida?", "info_seguros"),
    ("¿Cómo puedo asegurar mi auto?", "info_seguros"),
    ("Hola, necesito información sobre seguros de viaje", "info_seguros"),
    ("¿Qué ventajas tiene contratar un seguro de vida?", "info_seguros"),
    ("Quisiera saber más sobre seguros de auto", "info_seguros"),
    ("¿Cómo contratar un seguro de viaje?", "info_seguros"),
    ("¿Qué me cubre un seguro de vida?", "info_seguros"),
    ("Hola, ¿cómo puedo asegurar mi coche?", "info_seguros"),
    ("Quiero información sobre seguros de viaje, por favor", "info_seguros"),
    ("¿Qué tipos de seguros de vida ofrecen?", "info_seguros"),
    ("¿Cuáles son las opciones para asegurar un auto?", "info_seguros"),
    ("Hola, necesito saber sobre seguros de viaje", "info_seguros"),
    ("¿Qué coberturas tiene un seguro de vida?", "info_seguros"),
    ("¿Cómo obtengo un seguro de auto?", "info_seguros"),
    ("Hola, ¿me puedes dar detalles sobre los seguros de viaje?", "info_seguros"),
    ("¿Qué incluye un seguro de vida?", "info_seguros"),
    ("¿Qué opciones hay para asegurar mi coche?", "info_seguros"),
    ("Quiero saber sobre los seguros de viaje", "info_seguros"),
    ("¿Qué cubre un seguro de vida?", "info_seguros"),
    ("¿Qué tipos de seguros de coche tienen?", "info_seguros"),
    ("Hola, necesito información sobre seguros de viaje", "info_seguros"),
    ("¿Cuáles son las ventajas de un seguro de vida?", "info_seguros"),
    ("¿Cómo aseguro mi auto?", "info_seguros"),
    ("Hola, ¿qué opciones tienen para seguros de viaje?", "info_seguros"),
    ("¿Qué cubre un seguro de vida?", "info_seguros"),
    ("¿Cómo puedo asegurar mi carro?", "info_seguros"),
    ("Quiero información sobre seguros de viaje", "info_seguros"),
    ("¿Qué beneficios tiene un seguro de vida?", "info_seguros"),
    ("Hola, ¿me puedes hablar sobre los seguros de coche?", "info_seguros"),
    ("¿Cómo funciona un seguro de viaje?", "info_seguros"),
    ("¿Qué coberturas tiene un seguro de vida?", "info_seguros"),
    ("tengo una duda sobre los seguros, puedes darme informacion?", "info_seguros"),
    ("¿Cómo obtengo un seguro de coche?", "info_seguros"),
    ("Hola, necesito información sobre seguros de viaje", "info_seguros"),
    ("¿Qué ventajas tiene un seguro de vida?", "info_seguros"),
    ("Quiero saber más sobre los seguros de auto", "info_seguros"),
    ("¿Cómo contrato un seguro de viaje?", "info_seguros"),
    ("¿Qué me cubre un seguro de vida?", "info_seguros"),
    ("Hola, ¿cómo puedo asegurar mi coche?", "info_seguros"),
    ("Quiero información sobre seguros de viaje", "info_seguros"),
    ("¿Qué tipos de seguros de vida ofrecen?", "info_seguros"),
    ("¿Cuáles son las opciones para asegurar un auto?", "info_seguros"),
    ("Hola, necesito saber sobre seguros de viaje", "info_seguros"),
    ("¿Qué coberturas tiene un seguro de vida?", "info_seguros"),
    ("¿Cómo obtengo un seguro de auto?", "info_seguros"),
    ("Hola, ¿me puedes dar detalles sobre los seguros de viaje?", "info_seguros"),
    ("¿Qué incluye un seguro de vida?", "info_seguros"),
    ("¿Qué opciones hay para asegurar mi coche?", "info_seguros"),
    ("Quiero saber sobre los seguros de viaje", "info_seguros"),
    ("¿Qué cubre un seguro de vida?", "info_seguros"),
    ("¿Qué tipos de seguros de coche tienen?", "info_seguros"),
    ("Hola, necesito información sobre seguros de viaje", "info_seguros"),
    ("¿Cuáles son las ventajas de un seguro de vida?", "info_seguros"),
    ("¿Cómo aseguro mi auto?", "info_seguros"),
    ("Hola, ¿qué opciones tienen para seguros de viaje?", "info_seguros"),

    #informacion tarjetas 80 ejemplos
    ("¿Qué tipos de tarjetas de débito ofrecen?", "info_tarjetas"),
    ("Hola, ¿puedes darme información sobre tarjetas de crédito?", "info_tarjetas"),
    ("Quisiera saber más sobre las tarjetas prepago, ¿me puedes ayudar?", "info_tarjetas"),
    ("¿Cuáles son las opciones de tarjetas de débito?", "info_tarjetas"),
    ("quiero adquirir una tarjeta de prepago", "info_tarjetas"),
    ("Hola, ¿qué tarjetas de crédito tienen disponibles?", "info_tarjetas"),
    ("Necesito información sobre las tarjetas prepago", "info_tarjetas"),
    ("¿Qué beneficios tiene una tarjeta de débito?", "info_tarjetas"),
    ("Hola, ¿qué opciones hay para tarjetas de crédito?", "info_tarjetas"),
    ("¿Qué ventajas tienen las tarjetas prepago?", "info_tarjetas"),
    ("Quisiera conocer las características de las tarjetas de débito", "info_tarjetas"),
    ("tengo una duda sobre los tipos de tarjetas, puedes darme informacion?", "info_tarjetas"),
    ("¿Qué incluye una tarjeta de crédito?", "info_tarjetas"),
    ("Hola, ¿cómo funcionan las tarjetas prepago?", "info_tarjetas"),
    ("¿Cómo puedo obtener una tarjeta de débito?", "info_tarjetas"),
    ("Hola, necesito información sobre las tarjetas de crédito", "info_tarjetas"),
    ("¿Qué tipos de tarjetas prepago existen?", "info_tarjetas"),
    ("¿Cuáles son los requisitos para una tarjeta de débito?", "info_tarjetas"),
    ("Hola, ¿puedo obtener detalles sobre las tarjetas de crédito?", "info_tarjetas"),
    ("¿Cómo se usan las tarjetas prepago?", "info_tarjetas"),
    ("hola buen dia, podrias darme las caracteriticas de las tarjetas", "info_tarjetas"),
    ("¿Qué beneficios ofrecen las tarjetas de débito?", "info_tarjetas"),
    ("Hola, quiero saber más sobre las tarjetas de crédito", "info_tarjetas"),
    ("¿Qué opciones tienen para tarjetas prepago?", "info_tarjetas"),
    ("¿Cuáles son las características de una tarjeta de débito?", "info_tarjetas"),
    ("Hola, necesito información sobre tarjetas de crédito", "info_tarjetas"),
    ("¿Cómo obtengo una tarjeta prepago?", "info_tarjetas"),
    ("¿Qué ventajas tienen las tarjetas de débito?", "info_tarjetas"),
    ("Hola, ¿qué tipos de tarjetas de crédito hay?", "info_tarjetas"),
    ("Quiero saber sobre las tarjetas prepago", "info_tarjetas"),
    ("¿Cómo puedo solicitar una tarjeta de débito?", "info_tarjetas"),
    ("Hola, ¿me puedes explicar las tarjetas de crédito?", "info_tarjetas"),
    ("¿Cuáles son los beneficios de las tarjetas prepago?", "info_tarjetas"),
    ("¿Qué opciones de tarjetas de débito tienen?", "info_tarjetas"),
    ("Hola, ¿qué puedo saber sobre las tarjetas de crédito?", "info_tarjetas"),
    ("Necesito información sobre las tarjetas prepago", "info_tarjetas"),
    ("¿Qué tipos de tarjetas de débito tienen?", "info_tarjetas"),
    ("Hola, ¿qué tarjetas de crédito están disponibles?", "info_tarjetas"),
    ("Quiero conocer más sobre las tarjetas prepago", "info_tarjetas"),
    ("¿Cuáles son los beneficios de una tarjeta de débito?", "info_tarjetas"),
    ("Hola, ¿puedes hablarme sobre las tarjetas de crédito?", "info_tarjetas"),
    ("¿Qué ventajas ofrecen las tarjetas prepago?", "info_tarjetas"),
    ("¿Qué incluye una tarjeta de débito?", "info_tarjetas"),
    ("Hola, necesito saber sobre las tarjetas de crédito", "info_tarjetas"),
    ("¿Qué características tienen las tarjetas prepago?", "info_tarjetas"),
    ("¿Cómo puedo obtener una tarjeta de débito?", "info_tarjetas"),
    ("Hola, ¿qué opciones hay para tarjetas de crédito?", "info_tarjetas"),
    ("¿Qué tipos de tarjetas prepago ofrecen?", "info_tarjetas"),
    ("¿Qué debo hacer para obtener una tarjeta de débito?", "info_tarjetas"),
    ("Hola, quiero saber más sobre las tarjetas de crédito", "info_tarjetas"),
    ("¿Cómo funcionan las tarjetas prepago?", "info_tarjetas"),
    ("Quiero información sobre las tarjetas de débito", "info_tarjetas"),
    ("Hola, ¿qué beneficios tienen las tarjetas de crédito?", "info_tarjetas"),
    ("¿Qué opciones hay para tarjetas prepago?", "info_tarjetas"),
    ("¿Cuáles son los tipos de tarjetas de débito?", "info_tarjetas"),
    ("Hola, ¿puedes explicarme las tarjetas de crédito?", "info_tarjetas"),
    ("Necesito saber sobre las tarjetas prepago", "info_tarjetas"),
    ("¿Qué ventajas tienen las tarjetas de débito?", "info_tarjetas"),
    ("Hola, ¿qué tipos de tarjetas de crédito tienen?", "info_tarjetas"),
    ("Quisiera saber sobre las tarjetas prepago", "info_tarjetas"),
    ("¿Qué características tienen las tarjetas de débito?", "info_tarjetas"),
    ("Hola, necesito información sobre tarjetas de crédito", "info_tarjetas"),
    ("¿Qué beneficios tienen las tarjetas prepago?", "info_tarjetas"),
    ("¿Cuáles son las opciones para tarjetas de débito?", "info_tarjetas"),
    ("Hola, ¿qué debo saber sobre las tarjetas de crédito?", "info_tarjetas"),
    ("¿Qué ventajas ofrecen las tarjetas prepago?", "info_tarjetas"),
    ("Quiero saber más sobre las tarjetas de débito", "info_tarjetas"),
    ("Hola, necesito detalles sobre las tarjetas de crédito", "info_tarjetas"),
    ("¿Qué opciones tienen para tarjetas prepago?", "info_tarjetas"),
    ("¿Cómo puedo solicitar una tarjeta de débito?", "info_tarjetas"),
    ("Hola, ¿puedes darme información sobre tarjetas de crédito?", "info_tarjetas"),
    ("Quiero saber más sobre las tarjetas prepago", "info_tarjetas"),
    ("¿Qué debo hacer para obtener una tarjeta de débito?", "info_tarjetas"),
    ("Hola, necesito saber sobre las tarjetas de crédito", "info_tarjetas"),
    ("¿Qué características tienen las tarjetas prepago?", "info_tarjetas"),
    ("¿Qué beneficios tienen las tarjetas de débito?", "info_tarjetas"),
    ("Hola, quiero saber más sobre las tarjetas de crédito", "info_tarjetas"),
    ("¿Cómo funcionan las tarjetas prepago?", "info_tarjetas"),
    ("¿Qué tipos de tarjetas de débito tienen?", "info_tarjetas"),
    ("Hola, ¿qué opciones hay para tarjetas de crédito?", "info_tarjetas"),
    ("Necesito información sobre las tarjetas prepago", "info_tarjetas"),
    ("Me gustaria tramitar una tarjeta", "info_tarjetas"),
    ("¿Cuáles son los beneficios de las tarjetas de débito?", "info_tarjetas"),
    ("Hola, quiero saber sobre las tarjetas de crédito", "info_tarjetas"),
    ("¿Qué ventajas tienen las tarjetas prepago?", "info_tarjetas"),
    ("Dame informes sobre tarjetas", "info_tarjetas"),
    ("Dame informes sobre las tarjetas", "info_tarjetas"),

    #informacion general 80 ejemplos
    ("¿Me podrías dar información?", "info_general"),
    ("que productos ofreces?", "info_general"),
    ("Quisiera saber más sobre esto", "info_general"),
    ("¿Tienes detalles sobre el tema?", "info_general"),
    ("Podrías proporcionarme informes, por favor", "info_general"),
    ("¿Dónde puedo encontrar más información?", "info_general"),
    ("¿Puedes contarme más?", "info_general"),
    ("Necesito más datos sobre esto", "info_general"),
    ("¿Me puedes dar un resumen?", "info_general"),
    ("Quisiera entender más", "info_general"),
    ("¿Podrías explicarme mejor?", "info_general"),
    ("¿Tienes más detalles?", "info_general"),
    ("¿Dónde puedo leer más sobre esto?", "info_general"),
    ("Me gustaría saber más, por favor", "info_general"),
    ("¿Puedes ofrecerme información adicional?", "info_general"),
    ("¿Me podrías proporcionar un informe?", "info_general"),
    ("Necesito saber más", "info_general"),
    ("¿Tienes algún documento con más detalles?", "info_general"),
    ("Podrías informarme al respecto", "info_general"),
    ("¿Hay más información disponible?", "info_general"),
    ("¿Dónde encuentro más detalles?", "info_general"),
    ("Por favor, dame más información", "info_general"),
    ("¿Podrías ampliar la información?", "info_general"),
    ("Me gustaría recibir más datos", "info_general"),
    ("¿Puedes darme más información?", "info_general"),
    ("Solicito información detallada", "info_general"),
    ("Necesito un informe completo", "info_general"),
    ("¿Tienes información disponible?", "info_general"),
    ("¿Dónde puedo obtener más información?", "info_general"),
    ("Por favor, proporcióname más detalles", "info_general"),
    ("Quisiera más información, por favor", "info_general"),
    ("¿Puedes darme más detalles?", "info_general"),
    ("Solicito más información", "info_general"),
    ("¿Dónde puedo buscar más datos?", "info_general"),
    ("Por favor, infórmame más", "info_general"),
    ("¿Podrías ofrecer más información?", "info_general"),
    ("Me interesa saber más", "info_general"),
    ("¿Tienes información adicional?", "info_general"),
    ("¿Puedes proporcionar un informe?", "info_general"),
    ("¿Dónde encuentro más información?", "info_general"),
    ("Por favor, dime más sobre esto", "info_general"),
    ("Necesito más detalles", "info_general"),
    ("¿Podrías darme más datos?", "info_general"),
    ("¿Hay más información que pueda revisar?", "info_general"),
    ("¿Puedes compartir más información?", "info_general"),
    ("Me gustaría conocer más", "info_general"),
    ("Solicito detalles adicionales", "info_general"),
    ("¿Dónde puedo obtener detalles?", "info_general"),
    ("Por favor, amplíame la información", "info_general"),
    ("Quiero saber más, por favor", "info_general"),
    ("¿Puedes ofrecer más detalles?", "info_general"),
    ("Solicito informes detallados", "info_general"),
    ("¿Hay más detalles disponibles?", "info_general"),
    ("¿Dónde puedo hallar más información?", "info_general"),
    ("Por favor, envíame más información", "info_general"),
    ("Necesito más información, gracias", "info_general"),
    ("¿Podrías enviarme un informe?", "info_general"),
    ("¿Hay más detalles que puedas compartir?", "info_general"),
    ("Quisiera más detalles, por favor", "info_general"),
    ("¿Tienes más datos?", "info_general"),
    ("¿Dónde encuentro información adicional?", "info_general"),
    ("Por favor, dame detalles adicionales", "info_general"),
    ("Quisiera recibir más informes", "info_general"),
    ("¿Podrías darme información completa?", "info_general"),
    ("Solicito un informe detallado", "info_general"),
    ("¿Dónde hay más información?", "info_general"),
    ("Por favor, proporcióname más datos", "info_general"),
    ("Necesito información adicional", "info_general"),
    ("¿Podrías ofrecer más detalles sobre esto?", "info_general"),
    ("¿Dónde puedo encontrar más detalles?", "info_general"),
    ("Me interesa recibir más información", "info_general"),
    ("¿Tienes un informe detallado?", "info_general"),
    ("¿Puedes darme más datos?", "info_general"),
    ("Por favor, infórmame sobre esto", "info_general"),
    ("Necesito detalles adicionales", "info_general"),
    ("¿Podrías enviarme información?", "info_general"),
    ("¿Dónde obtengo más datos?", "info_general"),
    ("Por favor, comparte más información", "info_general"),
    ("Quisiera un informe más completo", "info_general"),
    ("¿Puedes proporcionar más detalles?", "info_general"),
    ("Solicito información ampliada", "info_general"),
    ("dame informes generales", "info_general"),
    ("dame informes", "info_general"),


 ]




# Aumentar datos mediante técnicas de aumento de datos
def augment_data(text, num_variations):
    words = text.split()
    augmented_texts = []
    for _ in range(num_variations):
        random.shuffle(words)
        augmented_texts.append(' '.join(words))
    return augmented_texts
    

# Aplicar aumento de datos a clases con menor rendimiento
augmented_data = []
for text, label in data:
    augmented_data.append((text, label))
    if label in ["info_prestamo", "info_seguros", "info_tarjetas", "info_general"]:
        augmented_texts = augment_data(text, 3)
        for aug_text in augmented_texts:
            augmented_data.append((aug_text, label))

# Separar textos y etiquetas
texts, labels = zip(*augmented_data)

# Aplicar preprocesamiento
texts = [preprocess(text) for text in texts]

# Convertir etiquetas a índices
label_map = {"consultar_saldo": 0, "cancelar_tarjeta": 1, "info_prestamo": 2, "info_seguros": 3, "info_tarjetas": 4, "info_general": 5}
y = [label_map[label] for label in labels]

# Verificar las etiquetas únicas antes del entrenamiento
unique_labels = np.unique(y)
print("Etiquetas únicas en los datos de entrenamiento:", unique_labels)

# Crear el vectorizador y el modelo SVM
vectorizer = TfidfVectorizer(ngram_range=(2, 3))

# Dividir los datos en conjuntos de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(texts, y, test_size=0.2, random_state=42)

# Ajustar el vectorizador con los datos de entrenamiento
X_train_tfidf = vectorizer.fit_transform(X_train)

# Crear el modelo SVM con pesos balanceados y regularización
svm_model = SVC(probability=True, class_weight='balanced')

# Parámetros para la búsqueda en cuadrícula (Grid Search)
param_grid = {
    'C': [0.01, 0.1, 1, 10, 100],
    'kernel': ['linear', 'rbf']
}

# Búsqueda en cuadrícula con validación cruzada
grid_search = GridSearchCV(svm_model, param_grid, cv=5, scoring='accuracy')

# Entrenar el modelo con los datos de entrenamiento transformados
grid_search.fit(X_train_tfidf, y_train)

# Evaluar el modelo
best_model = grid_search.best_estimator_
X_test_tfidf = vectorizer.transform(X_test)
y_pred = best_model.predict(X_test_tfidf)

# Verificar las etiquetas únicas en las predicciones
unique_pred_labels = np.unique(y_pred)
print("Etiquetas únicas en las predicciones:", unique_pred_labels)

# Imprimir la matriz de confusión
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

# Imprimir el reporte de clasificación
class_report = classification_report(y_test, y_pred, target_names=label_map.keys())
print("\nClassification Report:")
print(class_report)

# Validación cruzada con el mejor modelo
cross_val_scores = cross_val_score(best_model, vectorizer.transform(texts), y, cv=10, scoring='accuracy')
print("Cross-validation scores:", cross_val_scores)
print("Mean cross-validation score:", cross_val_scores.mean())

# Guardar el vectorizador y el modelo entrenado
with open('tfidf_vectorizer.pkl', 'wb') as f:
    pickle.dump(vectorizer, f)

with open('svm_model.pkl', 'wb') as f:
    pickle.dump(best_model, f)